### PR TITLE
Changed UI to material design

### PR DESCRIPTION
**Pull request by GuilleDF**
Main changes:
 - Updated all icons to the official material design icons
 - Default theme in 5.0+ devices is Material.Light.DarkActionBar
 - Default theme on other devices is Sherlock.Light.DarkActionBar (just to provide a little bit of consistency among versions)
 - Moved manual input button from action bar to a floating action button
 - Added swipe to refresh gesture

### CODE REVIEW

**Comment by ruiaraujo** [comment]
Good work.

I am not sure about the Fab button since the manual mode is rarely used and it is more for debug purposes.
Also it doesn't compile.
I think you forgot to add back the files on drawable-*-v21.

**Comment by GuilleDF** [comment]
Whoops, sorry about the drawables! Now it compiles.
I guess you're right about the FAB, I'll move it back to the action bar.

**Comment by ruiaraujo** [comment]
Where did you get the new icons from?

They look different from my Nexus 6.0 settings?

**Comment by GuilleDF** [comment]
I got the icons from here: https://www.google.com/design/icons/
All I can think of is maybe I didn't select the correct actions?

**Pull request merged**
